version: '3.3'
services:
    postgres:
        container_name: xy_inc_postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        networks:
            - production-network

    xyinc:
        container_name: xy-inc
        image: volgarini/xy-inc
        restart: always
        ports:
            - '8081:8081'
        depends_on:
            - postgres
        networks:
            - production-network

networks:
    production-network:
        driver: bridge