version: '3.3'
services:
  postgres:
    container_name: xy_inc_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - production-network
   
  pgadmin:
    container_name: xy_inc_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: xyinc
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '9595:80'
    networks:
      - production-network      
networks: 
  production-network:
        driver: bridge